apiVersion: v1
kind: Service
metadata:
  name: mscredits
  namespace: prod
spec:
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: mscredits
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    app: mscredits
  name: mscredits
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscredits
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mscredits
    spec:
      containers:
        - image: ibmdigitalbank/mscredits:latest
          name: mscredits
          ports:
            - containerPort: 8082
              name: http
        