apiVersion: v1
kind: Service
metadata:
  name: mstransactions
  namespace: default
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: mstransactions
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    app: mstransactions
  name: mstransactions
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mstransactions
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mstransactions
    spec:
      containers:
        - image: ibmdigitalbank/mstransactions:latest
          name: mstransactions
          ports:
            - containerPort: 8080
              name: http