apiVersion: v1
kind: Service
metadata:
  name: mscomptes
  namespace: default
spec:
  ports:
  - name: http
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: mscomptes
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    app: mscomptes
  name: mscomptes
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mscomptes
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mscomptes
    spec:
      containers:
        - image: ibmdigitalbank/mscomptes:latest
          name: mscomptes
          ports:
            - containerPort: 8081
              name: http